#指定基础镜像，在其上进行定制
FROM openjdk:17-jdk-alpine

#维护者信息
MAINTAINER wei

#这里的 /tmp 目录就会在运行时自动挂载为匿名卷，任何向 /tmp 中写入的信息都不会记录进容器存储层
VOLUME /tmp

#复制上下文目录下的target/springboot-demo-docker-0.0.1-SNAPSHOT.jar 到容器里
COPY lamb_detection_system-1.0-SNAPSHOT.jar lamb-1.0.0.jar


#声明运行时容器提供服务端口，这只是一个声明，在运行时并不会因为这个声明应用就会开启这个端口的服务
EXPOSE 9999

#指定容器启动程序及参数   <ENTRYPOINT> "<CMD>"
ENTRYPOINT ["java","-jar","lamb-1.0.0.jar"]